In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('../cyberbullying_datasets/course_dataset/cb_chi_compressed.csv.gz')
df.head()

,idiot,stupid,moron,dumb,fuck,love,xa,comment,shut,fool,...,blue cheese,suck bitach,bitach,follow jackass,jackass hate,free publicity,publicity,miss idiot,village miss,bullying
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [3]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['bullying'], axis=1), df['bullying'], 
                                                    test_size=.2, random_state=0, stratify=df['bullying'])

In [17]:
grid = {
    'C': [1, 5, 10, 15],
    'penalty': ['l2', 'l1', 'elasticnet'],
    'solver': ['lbfgs', 'liblinear', 'saga'],
    'l1_ratio': [0.2, 0.5, 0.8]
}

grid_search = GridSearchCV(LogisticRegression(random_state=0), grid, cv=3, scoring='accuracy', verbose=2).fit(X_train, y_train)

Fitting 3 folds for each of 108 candidates, totalling 324 fits

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   1.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   0.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   0.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.2, penalty=l2, solver=saga; total time=   4.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.2, penalty=l2, solver=saga; total time=   4.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.2, penalty=l2, solver=saga; total time=   5.0s
[CV] END ........C=1, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.1s
[CV] END ........C=1, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=1, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.2, penalty=l1, solver=saga; total time=  13.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.2, penalty=l1, solver=saga; total time=  12.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.2, penalty=l1, solver=saga; total time=  12.1s
[CV] END C=1, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=1, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=   5.8s
[CV] END .C=1, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=   5.8s
[CV] END .C=1, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=   6.2s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.5, penalty=l2, solver=saga; total time=   4.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.5, penalty=l2, solver=saga; total time=   4.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.5, penalty=l2, solver=saga; total time=   4.6s
[CV] END ........C=1, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=1, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=1, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.5, penalty=l1, solver=saga; total time=  13.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.5, penalty=l1, solver=saga; total time=  11.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.5, penalty=l1, solver=saga; total time=  11.8s
[CV] END C=1, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=1, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   5.4s
[CV] END .C=1, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   5.5s
[CV] END .C=1, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   5.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=1, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.8, penalty=l2, solver=saga; total time=   4.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.8, penalty=l2, solver=saga; total time=   4.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.8, penalty=l2, solver=saga; total time=   4.7s
[CV] END ........C=1, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=1, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=1, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=1, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.8, penalty=l1, solver=saga; total time=  17.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.8, penalty=l1, solver=saga; total time=  20.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=1, l1_ratio=0.8, penalty=l1, solver=saga; total time=  20.5s
[CV] END C=1, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=1, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=1, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  12.8s
[CV] END .C=1, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  12.8s
[CV] END .C=1, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  12.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   0.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   1.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   1.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.2, penalty=l2, solver=saga; total time=   8.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.2, penalty=l2, solver=saga; total time=   7.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.2, penalty=l2, solver=saga; total time=   8.1s
[CV] END ........C=5, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=5, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=5, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.2, penalty=l1, solver=saga; total time=  27.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.2, penalty=l1, solver=saga; total time=  27.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.2, penalty=l1, solver=saga; total time=  27.8s
[CV] END C=5, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=5, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=5, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=5, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=5, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  12.9s
[CV] END .C=5, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  12.2s
[CV] END .C=5, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  12.6s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.6s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   1.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.5, penalty=l2, solver=saga; total time=   8.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.5, penalty=l2, solver=saga; total time=   7.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.5, penalty=l2, solver=saga; total time=  12.1s
[CV] END ........C=5, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.1s
[CV] END ........C=5, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=5, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.5, penalty=l1, solver=saga; total time=  33.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.5, penalty=l1, solver=saga; total time=  26.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.5, penalty=l1, solver=saga; total time=  26.5s
[CV] END C=5, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=5, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=5, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=5, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  15.0s
[CV] END .C=5, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  15.1s
[CV] END .C=5, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  14.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   0.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=5, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   1.2s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.8, penalty=l2, solver=saga; total time=   7.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.8, penalty=l2, solver=saga; total time=   8.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.8, penalty=l2, solver=saga; total time=   8.3s
[CV] END ........C=5, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=5, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END ........C=5, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ....C=5, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END .........C=5, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.1s
[CV] END C=5, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=5, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=5, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=5, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=5, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=5, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  26.0s
[CV] END .C=5, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  23.8s
[CV] END .C=5, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  28.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   0.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   0.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   1.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.2, penalty=l2, solver=saga; total time=  13.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.2, penalty=l2, solver=saga; total time=  12.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.2, penalty=l2, solver=saga; total time=  12.8s
[CV] END .......C=10, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=10, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=10, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.8s
[CV] END ...C=10, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.2, penalty=l1, solver=saga; total time=  27.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.2, penalty=l1, solver=saga; total time=  26.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.2, penalty=l1, solver=saga; total time=  28.1s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  21.8s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  25.3s
[CV] END C=10, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  31.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   1.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   1.6s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.5, penalty=l2, solver=saga; total time=  19.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.5, penalty=l2, solver=saga; total time=  16.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.5, penalty=l2, solver=saga; total time=  16.7s
[CV] END .......C=10, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=10, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=10, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.6s
[CV] END ...C=10, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.5, penalty=l1, solver=saga; total time=  38.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.5, penalty=l1, solver=saga; total time=  38.2s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.5, penalty=l1, solver=saga; total time=  43.5s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.1s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.1s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.1s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  41.4s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  40.7s
[CV] END C=10, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  38.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   1.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   1.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=10, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   1.6s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.8, penalty=l2, solver=saga; total time=  20.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.8, penalty=l2, solver=saga; total time=  13.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.8, penalty=l2, solver=saga; total time=  12.6s
[CV] END .......C=10, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=10, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=10, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=10, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.6s
[CV] END ...C=10, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=10, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.7s
[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  29.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  29.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=10, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  29.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   0.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   1.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.2, penalty=l2, solver=lbfgs; total time=   1.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.2, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.2, penalty=l2, solver=saga; total time=  17.1s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.2, penalty=l2, solver=saga; total time=  16.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.2, penalty=l2, solver=saga; total time=  15.8s
[CV] END .......C=15, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=15, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=15, l1_ratio=0.2, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.2, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.2, penalty=l1, solver=saga; total time=  28.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.2, penalty=l1, solver=saga; total time=  28.8s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.2, penalty=l1, solver=saga; total time=  28.8s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  26.1s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  26.2s
[CV] END C=15, l1_ratio=0.2, penalty=elasticnet, solver=saga; total time=  25.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   0.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   1.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.5, penalty=l2, solver=lbfgs; total time=   1.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.5, penalty=l2, solver=saga; total time=  16.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.5, penalty=l2, solver=saga; total time=  16.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.5, penalty=l2, solver=saga; total time=  15.6s
[CV] END .......C=15, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=15, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=15, l1_ratio=0.5, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.5, penalty=l1, solver=saga; total time=  28.7s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.5, penalty=l1, solver=saga; total time=  28.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.5, penalty=l1, solver=saga; total time=  28.3s
[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.1s
[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  28.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  29.2s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=15, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=  29.2s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   0.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   1.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .......C=15, l1_ratio=0.8, penalty=l2, solver=lbfgs; total time=   1.5s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.8, penalty=l2, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.8, penalty=l2, solver=saga; total time=  17.2s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.8, penalty=l2, solver=saga; total time=  15.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.8, penalty=l2, solver=saga; total time=  15.5s
[CV] END .......C=15, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=15, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s
[CV] END .......C=15, l1_ratio=0.8, penalty=l1, solver=lbfgs; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ...C=15, l1_ratio=0.8, penalty=l1, solver=liblinear; total time=   0.3s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.8, penalty=l1, solver=saga; total time=  27.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END ........C=15, l1_ratio=0.8, penalty=l1, solver=saga; total time=  28.2s
[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=lbfgs; total time=   0.0s
[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=liblinear; total time=   0.0s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  28.9s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  29.4s

C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
108 fits failed out of a total of 324.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py", line 72, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.73980767 0.73969471 0.73969471        nan 0.67950226 0.67961525
        nan        nan 0.71699556 0.73980767 0.73969471 0.73969471
        nan 0.67950226 0.67961525        nan        nan 0.69711988
 0.73980767 0.73969471 0.73969471        nan 0.67950226 0.67961525
        nan        nan 0.685601   0.75324611 0.75313327 0.75313331
        nan 0.71643028 0.71744681        nan        nan 0.74793848
 0.75324611 0.75313327 0.75313331        nan 0.71643028 0.71744681
        nan        nan 0.73766169 0.75324611 0.75313327 0.75313331
        nan 0.71643028 0.71744681        nan        nan 0.7252389
 0.7570857  0.75832791 0.75844083        nan 0.73269258 0.73619319
        nan        nan 0.75347206 0.7570857  0.75832791 0.75844083
        nan 0.73269258 0.73619319        nan        nan 0.74895477
 0.7570857  0.75832791 0.75844083        nan 0.73269258 0.73619319
        nan        nan 0.74274315 0.76002187 0.75990891 0.75990891
        nan 0.73032081 0.74037138        nan        nan 0.75708554
 0.76002187 0.75990891 0.75990891        nan 0.73032081 0.74037138
        nan        nan 0.75290705 0.76002187 0.75990891 0.75990891
        nan 0.73032081 0.74037138        nan        nan 0.74658296]
  warnings.warn(
C:\Users\sebal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=15, l1_ratio=0.8, penalty=elasticnet, solver=saga; total time=  28.5s

In [14]:
df.shape[0] * 0.2

2213.8

In [15]:
X_test

,idiot,stupid,moron,dumb,fuck,love,xa,comment,shut,fool,...,like blue,blue cheese,suck bitach,bitach,follow jackass,jackass hate,free publicity,publicity,miss idiot,village miss
5885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5041,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4558,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9814,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3611,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
grid_search.best_params_

{'C': 15, 'l1_ratio': 0.2, 'penalty': 'l2', 'solver': 'lbfgs'}

In [ ]:
lr = LogisticRegression(
    C=15, 
    penalty='l2', 
    solver='lbfgs', 
    random_state=0
).fit(X_train, y_train)
print(lr.score(X_test, y_test))
print(lr.score(X_train, y_train))

0.7800361336946703
0.862789384528515

In [22]:
print(classification_report(y_test, lr.predict(X_test)))

              precision    recall  f1-score   support

           0       0.75      0.84      0.79      1105
           1       0.82      0.72      0.77      1109

    accuracy                           0.78      2214
   macro avg       0.78      0.78      0.78      2214
weighted avg       0.78      0.78      0.78      2214