In [ ]:
# import pandas as pd
# ## Dimensjonsredusert data
# df = pd.read_csv('../cyberbullying_datasets/course_dataset/cb_pca_compressed.csv.gz')
# print(df.shape)
# df

(11069, 5054)

,0,1,2,3,4,5,6,7,8,9,...,5044,5045,5046,5047,5048,5049,5050,5051,5052,bullying
0,-0.003748,-0.048954,-0.069151,0.084546,0.008233,-0.014312,-0.009723,-0.009641,-0.015172,0.008260,...,0.003412,0.007631,-0.003388,0.004994,0.000746,-0.004898,-0.003012,-0.014150,0.002005,0
1,-0.001565,-0.023980,0.003006,-0.022443,-0.002304,-0.027674,-0.005291,-0.017112,-0.019287,-0.017033,...,0.013057,-0.001910,0.001519,0.009646,0.001589,-0.006602,-0.002261,-0.004432,0.005040,0
2,-0.004251,-0.052138,-0.072969,0.084539,0.011185,-0.023830,-0.010253,-0.022800,-0.032063,-0.033933,...,-0.006004,0.003505,0.001346,-0.010223,0.007614,-0.008483,-0.007602,-0.005475,-0.003848,0
3,-0.003423,-0.022526,-0.014378,-0.028744,-0.008518,-0.038433,-0.001054,-0.035205,-0.030519,-0.017821,...,-0.002257,-0.001410,0.003238,0.001222,-0.001801,0.000657,-0.000796,0.002350,-0.002063,0
4,0.084788,0.056795,0.001405,-0.012161,0.001172,-0.025218,0.000287,-0.028262,-0.017295,-0.017872,...,-0.000864,-0.004876,-0.002621,0.000072,0.002679,0.006323,-0.005275,-0.001869,-0.004433,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11064,-0.006585,-0.042067,-0.021027,-0.095850,-0.085647,0.164848,-0.041829,-0.028922,0.012892,-0.006415,...,-0.000776,-0.001097,0.011670,0.001710,-0.000271,-0.003725,-0.003314,0.000785,-0.007789,1
11065,-0.030027,0.008898,-0.011680,-0.032846,-0.008865,-0.039012,-0.025824,0.022510,0.007145,0.063641,...,0.000114,-0.003625,-0.002245,-0.004826,0.008195,0.002387,-0.001264,-0.006106,0.003767,1
11066,-0.004848,-0.016247,-0.008499,-0.025731,-0.004900,-0.026112,-0.001015,-0.016811,-0.013704,-0.003872,...,-0.005140,-0.000362,-0.008044,-0.006002,-0.001162,0.004293,0.009440,-0.003449,-0.007684,1
11067,-0.007937,-0.018541,-0.013011,-0.039139,-0.014678,-0.019609,0.008090,-0.033202,-0.027038,0.008981,...,-0.000005,-0.001362,0.005678,0.000438,-0.000036,-0.001461,0.003617,0.006093,0.000684,1
11068,-0.002083,-0.033310,-0.018209,-0.039160,-0.013913,-0.056474,-0.085665,0.094215,0.070035,-0.029987,...,0.005162,-0.002158,0.004033,0.004151,-0.003637,0.002555,-0.016198,-0.005096,-0.006407,1

In [1]:
import pandas as pd
## Chi-kvadrat data
df = pd.read_csv('../cyberbullying_datasets/course_dataset/cb_chi_compressed.csv.gz')
print(df.shape)
df

(11069, 5001)

,idiot,stupid,moron,dumb,fuck,love,xa,comment,shut,fool,...,blue cheese,suck bitach,bitach,follow jackass,jackass hate,free publicity,publicity,miss idiot,village miss,bullying
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11064,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11066,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11067,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11068,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [2]:
X = df.drop(["bullying"], axis=1)
y = df["bullying"]

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0, stratify=y
)

from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=0)

svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7728093947606143

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.86      0.79      1105
           1       0.83      0.69      0.75      1109

    accuracy                           0.77      2214
   macro avg       0.78      0.77      0.77      2214
weighted avg       0.78      0.77      0.77      2214

In [4]:
## Her har jeg testet ulike kernels! Fant ut at RBF er best!:)

kernels = ['linear', 'poly', 'rbf']
for k in kernels:
    model = SVC(kernel=k, C=1.0, gamma='scale', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Kernel: {k} → Accuracy: {acc:.4f}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred))

Kernel: linear → Accuracy: 0.7552
Accuracy: 0.7551942186088527

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.86      0.78      1105
           1       0.83      0.65      0.73      1109

    accuracy                           0.76      2214
   macro avg       0.77      0.76      0.75      2214
weighted avg       0.77      0.76      0.75      2214

Kernel: poly → Accuracy: 0.7407
Accuracy: 0.7407407407407407

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.63      0.71      1105
           1       0.70      0.85      0.77      1109

    accuracy                           0.74      2214
   macro avg       0.75      0.74      0.74      2214
weighted avg       0.75      0.74      0.74      2214

Kernel: rbf → Accuracy: 0.7728
Accuracy: 0.7728093947606143

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.86      0.79      1105
           1       0.83      0.69      0.75      1109

    accuracy                           0.77      2214
   macro avg       0.78      0.77      0.77      2214
weighted avg       0.78      0.77      0.77      2214

In [5]:
#Prøvde også grid search men det ga lavere accuracy en det over, så trenger ikke å se å nøye på dette her!

from sklearn.model_selection import GridSearchCV

params = {'C': [1, 10, 20], 'gamma': ['scale', 0.001, 0.01]}
grid = GridSearchCV(SVC(kernel='rbf'), param_grid=params, cv=5)
grid.fit(X_train, y_train)
print(grid.best_params_, grid.best_score_)

{'C': 1, 'gamma': 'scale'} 0.7570863918690005